In [ ]:
import pandas as pd

In [24]:
data = pd.read_excel("alumnos.xlsx")

In [14]:
print(data[data['Nombre']=='Ulises Martínez Gómez'])

   ID                 Nombre    Género       Carrera  Semestre  \
0   1  Ulises Martínez Gómez  Femenino  Arquitectura         4

   Calificación Promedio Local o Foráneo
0                   6.56           Local

In [ ]:
print(data[(data["Semestre"]==4) | (data["Género"]=='Femenino')])

      ID                    Nombre     Género                     Carrera  \
0      1     Ulises Martínez Gómez   Femenino                Arquitectura
3      4         Yahir Ortega Wong   Femenino                  Psicología
5      6   Ximena Xochitl Martínez   Femenino  Administración de Empresas
7      8        Diana Vega Ramírez   Femenino                     Derecho
8      9     Valeria Ramírez López  Masculino            Ingeniería Civil
..   ...                       ...        ...                         ...
191  192      Wilfredo Núñez Yáñez   Femenino               Mercadotecnia
192  193          Iván Pérez Núñez   Femenino  Administración de Empresas
193  194      Brenda Quintana Wong   Femenino  Administración de Empresas
196  197    Manuel Yáñez Hernández   Femenino                     Derecho
198  199  Eduardo Hernández Urbina   Femenino                    Medicina

     Semestre  Calificación Promedio Local o Foráneo
0           4                   6.56           Local
3           3                   6.86         Foráneo
5           9                   7.17         Foráneo
7           3                   7.48           Local
8           4                   6.65         Foráneo
..        ...                    ...             ...
191         1                   9.62           Local
192         5                   6.95           Local
193         2                   9.35         Foráneo
196         5                   8.99         Foráneo
198         8                   9.92         Foráneo

[115 rows x 7 columns]

**Ejercicios:**
1. Ingeniería en sistemas o Arquitectura
2. Calificación promedio >= 8.5 y pertenecen a los últimos 3 semestres (8°, 9° y 10°)
3. Locales con promedio mayor a 9.0 o foráneos con promedio mayor a 9.0
4. Primer semestre o décimo semestre

In [45]:
print(data[(data["Carrera"]=='Ingeniería en Sistemas' ) | (data["Carrera"]=='Arquitectura')])

      ID                    Nombre     Género                 Carrera  \
0      1     Ulises Martínez Gómez   Femenino            Arquitectura
1      2        Valeria López Wong  Masculino  Ingeniería en Sistemas
6      7         Sofía Pérez López  Masculino            Arquitectura
9     10      Iván Quintana Torres  Masculino            Arquitectura
10    11          Iván López Pérez   Femenino            Arquitectura
18    19    Laura Sánchez Quintana  Masculino            Arquitectura
25    26           Laura Wong Wong   Femenino  Ingeniería en Sistemas
26    27   Zaira Martínez Quintana  Masculino            Arquitectura
29    30   Manuel Hernández Ortega   Femenino  Ingeniería en Sistemas
30    31        Jessica Wong Yáñez  Masculino            Arquitectura
31    32    Sofía Hernández Torres  Masculino  Ingeniería en Sistemas
39    40        Iván Sánchez Pérez   Femenino            Arquitectura
40    41         Brenda López Wong   Femenino  Ingeniería en Sistemas
46    47    Manuel Hernández Yáñez  Masculino            Arquitectura
48    49         Laura Zamora Vega   Femenino  Ingeniería en Sistemas
57    58         Zaira Pérez Núñez  Masculino  Ingeniería en Sistemas
62    63     Ulises Ramírez Zamora   Femenino            Arquitectura
72    73      Laura Quintana López  Masculino  Ingeniería en Sistemas
80    81        Oscar Wong Ramírez   Femenino            Arquitectura
81    82        Hilda Xochitl Vega   Femenino  Ingeniería en Sistemas
88    89       Iván Zamora Sánchez  Masculino            Arquitectura
89    90       Jessica Gómez Núñez   Femenino  Ingeniería en Sistemas
97    98   Jessica Sánchez Xochitl  Masculino            Arquitectura
106  107     Quetzal Gómez Xochitl   Femenino  Ingeniería en Sistemas
109  110         Rafael Gómez Wong  Masculino            Arquitectura
114  115       Rafael Vega Xochitl   Femenino            Arquitectura
125  126  Wilfredo Ramírez Xochitl   Femenino            Arquitectura
138  139     Laura Martínez Urbina   Femenino  Ingeniería en Sistemas
139  140         Oscar López Pérez  Masculino  Ingeniería en Sistemas
145  146     Ximena Zamora Sánchez   Femenino  Ingeniería en Sistemas
164  165     Carlos Vega Hernández   Femenino  Ingeniería en Sistemas
169  170      Hilda Martínez Núñez   Femenino            Arquitectura
175  176        Diana Torres López  Masculino  Ingeniería en Sistemas
181  182     Fernanda Pérez Torres   Femenino            Arquitectura
186  187      Fernanda Pérez Núñez   Femenino  Ingeniería en Sistemas
190  191        Diana Torres Núñez  Masculino  Ingeniería en Sistemas

     Semestre  Calificación Promedio Local o Foráneo
0           4                   6.56           Local
1           2                   6.87           Local
6           5                   9.94           Local
9           1                   9.22         Foráneo
10          8                   7.58         Foráneo
18         10                   9.79           Local
25          2                   6.24         Foráneo
26          9                   7.79         Foráneo
29          7                   7.06         Foráneo
30          5                   6.87           Local
31         10                   7.91           Local
39          5                   8.02         Foráneo
40          1                   7.33           Local
46          8                   7.40           Local
48          2                   9.51         Foráneo
57          4                   9.94           Local
62          5                   7.76         Foráneo
72          4                   6.80           Local
80          2                   7.12         Foráneo
81          8                   9.40           Local
88          5                   6.91           Local
89          1                   8.21           Local
97          5                   9.15           Local
106         4                   8.07         Foráneo
109         2                   7.85           Local
114         4                   8.29           Local
125         7                   9.41           Local
138         7                   7.10           Local
139         6                   6.97           Local
145         1                   9.99         Foráneo
164         8                   9.68         Foráneo
169         3                   8.41           Local
175         4                   8.83         Foráneo
181         4                  10.00           Local
186         8                   9.50           Local
190         5                   9.67         Foráneo

In [42]:
data[(data["Calificación Promedio"]>=8.5) & (data["Semestre"]>=8)]

,ID,Nombre,Género,Carrera,Semestre,Calificación Promedio,Local o Foráneo
18,19,Laura Sánchez Quintana,Masculino,Arquitectura,10,9.79,Local
19,20,Ximena Yáñez López,Masculino,Medicina,8,9.79,Local
27,28,Fernanda Ramírez Xochitl,Masculino,Administración de Empresas,8,9.23,Local
35,36,Oscar Torres López,Masculino,Contaduría,10,9.99,Local
55,56,Oscar Xochitl Xochitl,Masculino,Ingeniería Civil,8,9.17,Local
65,66,Nadia Hernández Pérez,Femenino,Diseño Gráfico,10,9.78,Local
74,75,Oscar Ramírez Urbina,Masculino,Mercadotecnia,10,9.85,Local
81,82,Hilda Xochitl Vega,Femenino,Ingeniería en Sistemas,8,9.40,Local
92,93,Patricia López Hernández,Masculino,Medicina,10,9.80,Local
99,100,Zaira Sánchez Sánchez,Femenino,Administración de Empresas,8,8.75,Foráneo
102,103,Yahir Ramírez Hernández,Masculino,Contaduría,9,8.61,Foráneo
117,118,Alejandro Núñez Wong,Masculino,Administración de Empresas,8,9.13,Foráneo
163,164,Ximena Wong Ortega,Masculino,Diseño Gráfico,9,8.81,Foráneo
164,165,Carlos Vega Hernández,Femenino,Ingeniería en Sistemas,8,9.68,Foráneo
178,179,Jessica Ramírez Núñez,Femenino,Administración de Empresas,10,8.65,Foráneo
186,187,Fernanda Pérez Núñez,Femenino,Ingeniería en Sistemas,8,9.50,Local
197,198,Zaira López Urbina,Masculino,Administración de Empresas,10,8.94,Foráneo
198,199,Eduardo Hernández Urbina,Femenino,Medicina,8,9.92,Foráneo

In [41]:
data[(data["Calificación Promedio"]>=9)]

,ID,Nombre,Género,Carrera,Semestre,Calificación Promedio,Local o Foráneo
6,7,Sofía Pérez López,Masculino,Arquitectura,5,9.94,Local
9,10,Iván Quintana Torres,Masculino,Arquitectura,1,9.22,Foráneo
14,15,Quetzal Ramírez Gómez,Masculino,Ingeniería Civil,5,9.07,Foráneo
15,16,Diana Sánchez Wong,Masculino,Contaduría,1,9.82,Foráneo
18,19,Laura Sánchez Quintana,Masculino,Arquitectura,10,9.79,Local
19,20,Ximena Yáñez López,Masculino,Medicina,8,9.79,Local
27,28,Fernanda Ramírez Xochitl,Masculino,Administración de Empresas,8,9.23,Local
35,36,Oscar Torres López,Masculino,Contaduría,10,9.99,Local
36,37,Carlos Pérez Zamora,Femenino,Medicina,6,9.52,Local
38,39,Valeria Sánchez Martínez,Masculino,Psicología,2,9.56,Local
44,45,Laura Wong Núñez,Masculino,Medicina,3,9.53,Local
45,46,Fernanda Torres Wong,Masculino,Psicología,3,9.15,Local
47,48,Hilda Gómez Pérez,Femenino,Derecho,5,9.46,Foráneo
48,49,Laura Zamora Vega,Femenino,Ingeniería en Sistemas,2,9.51,Foráneo
51,52,Alejandro Zamora Pérez,Femenino,Diseño Gráfico,2,9.80,Foráneo
55,56,Oscar Xochitl Xochitl,Masculino,Ingeniería Civil,8,9.17,Local
57,58,Zaira Pérez Núñez,Masculino,Ingeniería en Sistemas,4,9.94,Local
65,66,Nadia Hernández Pérez,Femenino,Diseño Gráfico,10,9.78,Local
66,67,Yahir Vega Yáñez,Masculino,Derecho,5,9.01,Foráneo
70,71,Manuel Torres Pérez,Femenino,Derecho,6,9.04,Foráneo
71,72,Iván Wong Ramírez,Masculino,Contaduría,1,9.00,Local
74,75,Oscar Ramírez Urbina,Masculino,Mercadotecnia,10,9.85,Local
75,76,Yahir Ortega Sánchez,Masculino,Mercadotecnia,1,9.72,Foráneo
76,77,Manuel Pérez López,Masculino,Administración de Empresas,5,9.40,Local
81,82,Hilda Xochitl Vega,Femenino,Ingeniería en Sistemas,8,9.40,Local
82,83,Patricia Pérez Urbina,Femenino,Derecho,5,9.52,Foráneo
91,92,Kevin Ortega Hernández,Femenino,Contaduría,2,9.29,Foráneo
92,93,Patricia López Hernández,Masculino,Medicina,10,9.80,Local
94,95,Jessica Wong Sánchez,Masculino,Mercadotecnia,2,9.79,Local
97,98,Jessica Sánchez Xochitl,Masculino,Arquitectura,5,9.15,Local
101,102,Ximena Torres Ramírez,Masculino,Administración de Empresas,4,9.85,Local
111,112,Patricia Quintana Xochitl,Masculino,Diseño Gráfico,4,9.69,Local
112,113,Carlos Ramírez Wong,Femenino,Ingeniería Civil,5,9.28,Foráneo
117,118,Alejandro Núñez Wong,Masculino,Administración de Empresas,8,9.13,Foráneo
118,119,Kevin Vega López,Femenino,Ingeniería Civil,7,9.82,Foráneo
123,124,Hilda Xochitl Ramírez,Femenino,Psicología,1,9.60,Foráneo
125,126,Wilfredo Ramírez Xochitl,Femenino,Arquitectura,7,9.41,Local
126,127,Hilda Vega Urbina,Femenino,Psicología,1,9.91,Foráneo
130,131,Gabriel Núñez Urbina,Femenino,Medicina,5,9.66,Foráneo
136,137,Manuel Xochitl Urbina,Femenino,Mercadotecnia,3,9.54,Local
140,141,Zaira Pérez López,Masculino,Mercadotecnia,4,9.25,Local
145,146,Ximena Zamora Sánchez,Femenino,Ingeniería en Sistemas,1,9.99,Foráneo
152,153,Valeria Martínez Wong,Femenino,Diseño Gráfico,1,9.87,Foráneo
154,155,Laura Urbina Martínez,Femenino,Mercadotecnia,4,9.23,Local
155,156,Tadeo Ramírez Gómez,Masculino,Psicología,5,9.69,Foráneo
158,159,Jessica Torres López,Masculino,Medicina,3,9.02,Local
164,165,Carlos Vega Hernández,Femenino,Ingeniería en Sistemas,8,9.68,Foráneo
171,172,Eduardo Xochitl López,Femenino,Contaduría,5,9.19,Local
174,175,Oscar Pérez Torres,Femenino,Ingeniería Civil,3,9.83,Foráneo
181,182,Fernanda Pérez Torres,Femenino,Arquitectura,4,10.00,Local
186,187,Fernanda Pérez Núñez,Femenino,Ingeniería en Sistemas,8,9.50,Local
190,191,Diana Torres Núñez,Masculino,Ingeniería en Sistemas,5,9.67,Foráneo
191,192,Wilfredo Núñez Yáñez,Femenino,Mercadotecnia,1,9.62,Local
193,194,Brenda Quintana Wong,Femenino,Administración de Empresas,2,9.35,Foráneo
198,199,Eduardo Hernández Urbina,Femenino,Medicina,8,9.92,Foráneo

In [46]:
data[(data["Semestre"]==1) | (data["Semestre"]==10)]

,ID,Nombre,Género,Carrera,Semestre,Calificación Promedio,Local o Foráneo
2,3,Rafael Pérez Wong,Masculino,Contaduría,10,7.11,Local
9,10,Iván Quintana Torres,Masculino,Arquitectura,1,9.22,Foráneo
15,16,Diana Sánchez Wong,Masculino,Contaduría,1,9.82,Foráneo
18,19,Laura Sánchez Quintana,Masculino,Arquitectura,10,9.79,Local
22,23,Alejandro Quintana Quintana,Masculino,Administración de Empresas,1,6.92,Local
31,32,Sofía Hernández Torres,Masculino,Ingeniería en Sistemas,10,7.91,Local
32,33,Brenda Zamora López,Masculino,Administración de Empresas,10,6.27,Local
35,36,Oscar Torres López,Masculino,Contaduría,10,9.99,Local
40,41,Brenda López Wong,Femenino,Ingeniería en Sistemas,1,7.33,Local
65,66,Nadia Hernández Pérez,Femenino,Diseño Gráfico,10,9.78,Local
68,69,Kevin Vega Ortega,Femenino,Medicina,10,8.14,Foráneo
71,72,Iván Wong Ramírez,Masculino,Contaduría,1,9.00,Local
74,75,Oscar Ramírez Urbina,Masculino,Mercadotecnia,10,9.85,Local
75,76,Yahir Ortega Sánchez,Masculino,Mercadotecnia,1,9.72,Foráneo
84,85,Rafael Quintana Yáñez,Femenino,Contaduría,1,6.37,Local
89,90,Jessica Gómez Núñez,Femenino,Ingeniería en Sistemas,1,8.21,Local
92,93,Patricia López Hernández,Masculino,Medicina,10,9.80,Local
100,101,Iván Zamora Yáñez,Femenino,Administración de Empresas,10,6.16,Foráneo
120,121,Diana Martínez Xochitl,Masculino,Psicología,1,6.18,Local
123,124,Hilda Xochitl Ramírez,Femenino,Psicología,1,9.60,Foráneo
124,125,Jessica Ortega López,Femenino,Derecho,10,7.20,Foráneo
126,127,Hilda Vega Urbina,Femenino,Psicología,1,9.91,Foráneo
128,129,Hilda Pérez Ramírez,Masculino,Administración de Empresas,1,7.24,Foráneo
132,133,Valeria Vega Urbina,Masculino,Diseño Gráfico,1,7.06,Local
145,146,Ximena Zamora Sánchez,Femenino,Ingeniería en Sistemas,1,9.99,Foráneo
147,148,Carlos Núñez Ramírez,Femenino,Diseño Gráfico,10,8.12,Foráneo
152,153,Valeria Martínez Wong,Femenino,Diseño Gráfico,1,9.87,Foráneo
161,162,Quetzal Sánchez Hernández,Masculino,Diseño Gráfico,10,6.22,Local
170,171,Fernanda Yáñez Xochitl,Femenino,Mercadotecnia,10,7.29,Foráneo
173,174,Jessica López López,Femenino,Contaduría,10,8.22,Local
178,179,Jessica Ramírez Núñez,Femenino,Administración de Empresas,10,8.65,Foráneo
182,183,Carlos Sánchez Martínez,Masculino,Derecho,10,6.52,Foráneo
183,184,Eduardo Ortega Ortega,Masculino,Contaduría,1,7.64,Local
188,189,Nadia López Quintana,Femenino,Derecho,1,7.66,Foráneo
191,192,Wilfredo Núñez Yáñez,Femenino,Mercadotecnia,1,9.62,Local
197,198,Zaira López Urbina,Masculino,Administración de Empresas,10,8.94,Foráneo
199,200,Ulises Ortega Núñez,Masculino,Contaduría,1,7.17,Local